# Generated by Django 5.0 on 2023-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text_data', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='photos')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
