# Generated by Django 5.0 on 2023-12-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_text_coment_comment_text_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
